typography_spectrum: 0.1437529199756682
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6941720405593514
  lightness: 0.5736082228831947
  saturation: 0.46099568135105073
  rhythmicContrast: 0.7073418772779405
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6221917495131493
analytics:
  google: null
  facebook: null
  twitter: null
name: TobyMacLeod
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Welcome
description: This is where it all begins.
purpose: []
